services:
  redis:
    container_name: "jals_redis"
    image: "redis/redis-stack:latest"
    ports: 
      - "6379:6379"
  mongo:
    container_name: "jals_mongo"
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
  nginx:
    container_name: "jals_nginx"
    image: "nginx:latest"
    ports: 
      - "8080:80"
      - "433:433"
  api:
    container_name: "jals_api"
    image: "xwirkijowski/jals-api:latest"
    ports:
      - "4010:4010"
    depends_on:
      - redis
      - mongo
      - nginx