services:
  redis:
    container_name: "jals_redis"
    image: "redis/redis-stack:latest"
    ports: 
      - "10013:6379"
      - "10014:8001"
  mongo:
    container_name: "jals_mongo"
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "10012:27017"
  api:
    container_name: "jals_api"
    image: "xwirkijowski/jals-api:latest"
    ports:
      - "10011:4000"
    environment:
      NODE_ENV: "development"
      SERVER_HOST: api
      SERVER_PORT: "4000"
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      MONGO_DB: "jals2"
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SECRET_AXIOM: ${SECRET_AXIOM}
      SECRET_RESEND: ${SECRET_RESEND}
      SECRET_SENTRY: ${SECRET_SENTRY}
    depends_on:
      - redis
      - mongo
  client:
    container_name: "jals_client"
    image: "xwirkijowski/jals-client-dev"
    build:
      - context: /client
      - dockerfile: ./docker/dev.Dockerfile
    ports:
      - "10010:3000"
    environment:
      NODE_ENV: "development"
      API_STRING: "https://api.jals2.wirkijowski.dev/"
    depends_on:
      - redis
      - mongo
      - api