services:
  api:
    container_name: "jals_api"
    image: "xwirkijowski/jals-api:latest"
    ports:
      - "10021:4000"
    environment:
      NODE_ENV: "development"
      SERVER_HOST: api
      SERVER_PORT: "4000"
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      MONGO_DB: "jals2"
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SECRET_AXIOM: ${SECRET_AXIOM}
      SECRET_RESEND: ${SECRET_RESEND}
      SECRET_SENTRY: ${SECRET_SENTRY}
  client:
    container_name: "jals_client"
    image: "xwirkijowski/jals-client-dev"
    build:
      - context: /client
      - dockerfile: ./docker/dev.Dockerfile
    ports:
      - "10020:3000"
    environment:
      NODE_ENV: "development"
      API_STRING: "http://api:4000/"